plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'dagger.hilt.android.plugin'
}

android {
    namespace 'com.gmail.uli153.workdaymeter'
    compileSdk 35

    defaultConfig {
        applicationId "com.gmail.uli153.workdaymeter"
        minSdk 21
        targetSdk 35
        versionCode 210100000 // [MIN_SDK][MAJOR][MINOR][PATCH]
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
        multiDexEnabled true
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        staging {
            debuggable true
            minifyEnabled false
            applicationIdSuffix ".staging"
            versionNameSuffix "[S]"
            signingConfig signingConfigs.debug
        }
        debug {
            debuggable true
            minifyEnabled false
            applicationIdSuffix ".debug"
            versionNameSuffix "[D]"
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.15'
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
        exclude 'META-INF/gradle/incremental.annotation.processors'
    }
}

dependencies {
    def compose_version = '1.7.7'
    def room_version = "2.6.1"

    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.8.7"
    implementation 'androidx.lifecycle:lifecycle-service:2.8.7'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'

    implementation 'androidx.activity:activity-compose:1.10.0'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation 'androidx.compose.material3:material3:1.3.1'
//    implementation "androidx.compose.material:material-*:1.3.1"
//    implementation 'androidx.compose.material:material:1.3.1'
    implementation "androidx.navigation:navigation-compose:2.8.6"
//    implementation "androidx.hilt:hilt-navigation-compose:1.0.0"

    implementation "androidx.constraintlayout:constraintlayout-compose:1.0.1"
    implementation "io.coil-kt:coil-compose:2.6.0"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"

    // Room
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    // To use Kotlin annotation processing tool (ksp)
    ksp "androidx.room:room-compiler:$room_version"

    // Hilt
    implementation 'com.google.dagger:hilt-android:2.51.1'
    ksp 'com.google.dagger:hilt-compiler:2.51.1'

    implementation 'com.valentinilk.shimmer:compose-shimmer:1.0.4'
    implementation 'com.jakewharton.threetenabp:threetenabp:1.4.6'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.airbnb.android:lottie-compose:6.4.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"
}